### ISSUE TITLE
error when using package xrenner

### ISSUE THREAD

**Issue by nanji2** [amir-zeldes/xrenner#106]
when I run the following codes:

from xrenner import Xrenner

xrenner = Xrenner()

it displayed "NameError: name 'quit' is not defined"

**Comment by amir-zeldes** [comment]
Thanks for reporting this - can you give some more details on the environment in which this is happening? quit() is a Python built-in, though googling the error suggests that in some ipython (jupyter) environments it might not work as expected. Is this happening in a jupyter notebook? Can you also say what version of Python you're using?

**Comment by nanji2** [comment]
I’m using python 3.7.

I run it in the spyder IDE under anaconda. The whole error message as below:

**Comment by amir-zeldes** [comment]
I'm not entirely sure why this is happening, but since quit() is only used in one file (modules/xrenner_sequence.py) the easiest solution is to just replace it with sys.exit(). Try pulling from the dev branch and let me know if you still have a problem.
