### ISSUE TITLE
Please update Dependencies in requirements.txt

### ISSUE THREAD

**Issue by TerminalZero** [amir-zeldes/xrenner#110]
My pip install of xrenner had not been working. Only with these exact package versions did it spin up:
transformers==3.0.2
numpy>=1.20.0,<=1.24.4
scikit-learn==0.22.1

transformers package above 3.5.1: ModuleNotFoundError - No module named 'transformers.modeling_distilbert'
transformers package above 3.0.2: AttributeError - BasicTokenizer' object has no attribute 'strip_accents'
numpy package above 1.24.4: AttributeError module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the builtin `float`
scikit-learn package above 0.22.1: AttributeError OrdinalEncoder' object has no attribute 'handle_unknown'

Tested in python 3.8.2

**Comment by amir-zeldes** [comment]
Thanks for reporting - this project is not under active development so it's possible various libraries no longer play nicely with it. I'll update the requirements.
