### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by ftyers** [amir-zeldes/xrenner#51]
At the moment the code seems to be only working on python2, would it be possible to have a version that works with python3 ?

**Comment by amir-zeldes** [comment]
Hm.. Looks like I had a regression in one of the files and it slipped back to some .iterkeys()/items()... If you're not using the sklearn version, this should be easy to fix (some of the models are specific to certain python distributions). I'll commit something in a moment.

**Comment by amir-zeldes** [comment]
OK, try this: d3b0a14a10b02d01588c40165a739f57cff1bb33 and let me know if you still have any problems - thanks for reporting it!

**Comment by ftyers** [comment]
Thanks! :) I'm not a Python pro, this is how I'm trying to install it:
```
$ python3 setup.py install --prefix=/home/fran/local
```
I get a lot of errors about `print` statements (e.g. they aren't in python3 style `print()`). I've tried both the `master` and `develop` branches. How should I be checking out and "installing" (if I want to install in a prefix with `setup.py`) ?

This is the setup log: https://paste2.org/4Xm10K8I

**Comment by amir-zeldes** [comment]
I see the unit tests still have Python 2 print statements, but that shouldn't get invoked... Maybe setup tools do it somehow. There are also some relative imports that might be offending. I just updated the code again - you should be able to setup / install, but first see if you can run the unit tests:

  * Download the dev branch of the repo (as a zip, or clone with git), and unpack in a clean directory
  * Run python xrenner.py -t
  * If the unit tests go through successfully, then the only step left is to install as you did above, and if that doesn't work, then I need to figure out what the install tools are doing

Let me know if the unit tests run now, and if so, whether the install is now OK.

**Comment by ftyers** [comment]
It seems to install now fine, but I get:

```
$ python3 
Python 3.5.4 (default, Aug 12 2017, 14:08:14) 
[GCC 7.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xrenner
>>> x = xrenner.Xrenner()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fran/source/xrenner/xrenner/modules/xrenner_xrenner.py", line 32, in __init__
    self.load(model, override)
  File "/home/fran/source/xrenner/xrenner/modules/xrenner_xrenner.py", line 46, in load
    self.lex = LexData(self.model, self.override)
  File "/home/fran/source/xrenner/xrenner/modules/xrenner_lex.py", line 83, in __init__
    self.speaker_rules, self.non_speaker_rules = self.parse_coref_rules(self.read_delim(self.model_files['coref_rules.tab'], 'single'))
KeyError: 'coref_rules.tab'
>>> 
```

Am I missing a file ? 

Note: I get the same error with `-t`:

```
$ python3 xrenner.py -t

xrenner unit tests
====================
Reading test cases from test/tests.dat
Initializing xrenner model 'eng'

E
======================================================================
ERROR: setUpModule (modules.xrenner_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fran/source/xrenner/xrenner/modules/xrenner_test.py", line 104, in setUpModule
    xrenner = Xrenner("eng")
  File "/home/fran/source/xrenner/xrenner/modules/xrenner_xrenner.py", line 32, in __init__
    self.load(model, override)
  File "/home/fran/source/xrenner/xrenner/modules/xrenner_xrenner.py", line 46, in load
    self.lex = LexData(self.model, self.override)
  File "/home/fran/source/xrenner/xrenner/modules/xrenner_lex.py", line 83, in __init__
    self.speaker_rules, self.non_speaker_rules = self.parse_coref_rules(self.read_delim(self.model_files['coref_rules.tab'], 'single'))
KeyError: 'coref_rules.tab'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
```

**Comment by ftyers** [comment]
I found out I can fix it by unzipping the `eng.xrm` file in `models/`. Now the tests run fine:

```
$ python3 xrenner.py -t

xrenner unit tests
====================
Reading test cases from test/tests.dat
Initializing xrenner model 'eng'


Testing model integrity
------------------------------
Checking model files:  
.
Running markable method tests
------------------------------
Run atomic modifier test:  
.Run markable name test:  
.
Running coref method tests
------------------------------
Run affix morphology test:  
.Run apposition envelope test:  
.Run cardinality test:  
.Run dynamic hasa test:  
.Run entity dep test:  
.Run hasa test:  
.Run isa test:  
.Run verbal event coreference test:  
.
----------------------------------------------------------------------
Ran 11 tests in 2.604s

OK
```

But now I get:

```
$ python3 xrenner.py -o conll example_in.conll10 
Traceback (most recent call last):
  File "xrenner.py", line 134, in <module>
    split_data = [data[i:i + chunk_size] for i in xrange(0, len(data), chunk_size)]
NameError: name 'xrange' is not defined
```

However I'm able to run it using:

```
>>> from xrenner import Xrenner
>>> xrenner = Xrenner()
>>> my_conllx_result = open('example_in.conll10').read()
>>> print(xrenner.analyze(my_conllx_result,"conll"))
```

I'll make another issue for the xrange problem.
