### ISSUE TITLE
Case sensitivity in the pronouns.tab file

### ISSUE THREAD

**Issue by ftyers** [amir-zeldes/xrenner#62]
Should the pronouns file be case sensitive ? Or should it be possible to use lemmas in the pronouns file ? For languages with a case system, having to duplicate the list is a bit cumbersome.

**Comment by amir-zeldes** [comment]
Unsurprisingly, the need for case sensitivity arose from English 'I', but there are other languages where case plays an interesting role (e.g. German honorific Sie). It is a little annoying, but I think listing a full form lexicon of pronouns is usually a manageable task for most languages. The alternative is to do it by POS or lemma alone, which I suppose could be a switch in the config.ini. I wouldn't want to overcrowd it with settings though. Currently my thinking is, if an uppercase form is specified, then it only matches uppercase, but if it's lowercase in the file, either case is matched.

**Comment by ftyers** [comment]
@amir-zeldes that sounds like sensible behaviour to me.  Perhaps if the pronouns file is missing then it could go on POS and otherwise on the contents of the pronouns file ?

**Comment by amir-zeldes** [comment]
Yes, that might make sense. Although without the pronoun file, agreement classes will need to be specified exhaustively in the parse. The reason this never occurred to me is that I usually feed xrenner auto-parses without morphology, not a UD treebank complete with morphological information.

Actually I think making all files optional would be a good idea, except:

  * config.ini
  * coref_rules.tab

Without those the system won't know how to behave, or to look for any pairs. I suppose the entity files aren't really 100% necessary either...
