### ISSUE TITLE
Unclear documentation on stop_list.tab

### ISSUE THREAD

**Issue by asharkinasuit** [amir-zeldes/xrenner#66]
The [documentation for the stop list](https://corpling.uis.georgetown.edu/xrenner/doc/models.html#stop-list-tab) seems to contradict itself, suggesting first that words with @ behind them are used as stop entries when they're not the whole markable, then in the next sentence that such words are used as stop when they _are_ the whole markable. I would assume the latter is correct, but then still I have a bit of trouble wrapping my head around the stop_list.tab because in the English model's stop_list, I see Alfred@. If I'm not mistaken, that would mean this first name (and there are others) cannot be the head of a coreference chain, but that doesn't seem right.

Also when looking at some of the other issues (e.g. #53, #57), I think it wouldn't hurt to have a good look at the documentation as it appears now and make sure it is up-to-date with the software and that all the details are explained as well. For instance, with entity_deps it took me a while to figure out that the function label was probably one from the original Universal Dependencies set of functions, or one of the closely related sets mentioned in [the paper](http://nlp.stanford.edu/pubs/USD_LREC14_paper_camera_ready.pdf) (though those don't seem to have labels for each preposition).

**Comment by amir-zeldes** [comment]
Agreed, the documentation should be more up-to-date, thanks for spotting these issues. As noted in #65, the input for the English model is not any kind of Universal Dependencies, but the older Stanford Dependencies. 

I'm looking at the stoplist issue now, and the intention was originally to do what the documentation says: rule out certain items only if they were the entire markable text. However as you point out, that would be a bad idea for 'Alfred', so the list was somehow contaminated with some irrelevant entries. The reason why this hasn't caused problems is that a bug currently prevents this from ever executing here:

https://github.com/amir-zeldes/xrenner/blob/master/xrenner/modules/xrenner_xrenner.py#L505

I can easily fix this bug, but that would cause problems for Alfred etc., so I need to clean up the stoplist first. I will update this issue as soon as that is taken care of.
