### ISSUE TITLE
Warn about cycles in input dependency trees

### ISSUE THREAD

**Issue by zangsir** [amir-zeldes/xrenner#7]
When tested with wsj_0049, the current xrenner throws a RuntimeError: maximum recursion depth exceeded in cmp and fails to generate the output file.

**Comment by amir-zeldes** [comment]
This is likely caused by a cycle in a dependency tree as a result of parser postprocessing. I can't reproduce this with wsj_0049_hyph.conll10. Are you working with the old tokenized version? If so, please try the _hyph file and see if you still get the error.

**Comment by amir-zeldes** [comment]
This turned out to be a cycle in the conll file. It might still be a good idea to create some facility for dealing with cycles, offering a rudimentary solution and/or a warning to the user. I'm changing this to an enhancement.

**Comment by amir-zeldes** [comment]
The suggestion is:
- For each sentence, check for cycles before processing
- If a cycle is detected, issue out a warning
- OPTIONAL: create a simple strategy for removing cycles (e.g. making the detected offending token a root).
