### ISSUE TITLE
Xrenner.docname is not set unless running standalone

### ISSUE THREAD

**Issue by asharkinasuit** [amir-zeldes/xrenner#83]
Because LexData.\_\_int__ already sets its `docname` to "untitled", the check at `xrenner_xrenner.py:76` always fails and the `docname` is never set when xrenner is run from within a Python session. Since `docname` isn't set, the call to depedit later on fails because it uses `self.docname`, which is still unset. If xrenner is run independently, a filename will be found and this problem doesn't occur.

**Comment by amir-zeldes** [comment]
That's right, thanks!
